# Generated by Django 3.2.11 on 2022-02-19 16:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
