# Generated by Django 3.2.11 on 2022-01-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='thumbnail',
        ),
    ]
