# Generated by Django 3.2.11 on 2022-02-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_avatar_comment_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_img',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
