# Generated by Django 3.2.11 on 2022-03-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.ManyToManyField(blank=True, to='blog.Country'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
