# Generated by Django 3.2.11 on 2022-03-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='yashc.jpg', upload_to='images/'),
        ),
    ]
