# Generated by Django 3.2.11 on 2022-02-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='tiktok',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
