# Generated by Django 3.2.11 on 2022-02-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220209_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='author',
            name='philo',
            field=models.TextField(default=''),
        ),
    ]
