# Generated by Django 3.2.11 on 2022-03-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='images/avatar_auth.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_img',
            field=models.ImageField(default='images/default.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='images/yashc.jpg', upload_to='images'),
        ),
    ]
