# Generated by Django 3.2.11 on 2022-02-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220209_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='yashc.jpg', upload_to='images'),
        ),
    ]
